fold: null
framing: false
learning_rate: 0.001
weight: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDgAAADk0NzkxOTc1MTg5MjgwcQJYAwAAAGNwdXEDSwlOdHEEUS6AAl1xAFgOAAAAOTQ3
    OTE5NzUxODkyODBxAWEuCQAAAAAAAAAAAIA/DdTnP6uqjEKKfLZAamCvQNqoj0Deyv5A3lq4P9Su
    pEA=
- 0
- !!python/tuple
  - 9
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
